#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Project One',   url: 'proj-1'}
- {name: 'Project Two',   url: 'proj-2'}
- {name: 'Project Three', url: 'proj-3'}

#-------------------------------
# Contact Section

social:
- {icon: 'discord',  link: 'https://discord.gg/Nx8kwSBAFb'}
- {icon: 'twitter',   link: 'https://twitter.com/arcadebridge'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Arcade Bridge is a software company who specializes on game development. We make games and publish tools on multiple stores. Some of our tools are Hypercasual Runner Starter Kit and Hypercasual Arcade Idle Starter Kit. You can find both of them in the Unity Asset Store.'
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
